### ISSUE TITLE
"Failed in openOrCreateDatabase open_v2 failed" after 10.000 queries+

### ISSUE THREAD

**Issue by NicolasHofmairT23** [capacitor-community/sqlite#138]
**Describe the bug**
When running a lot of queries to SQLITE this error appears and the database stops working:

> `Failed in openOrCreateDatabase open_v2 failed`

I need to run around 34.000 queries to insert my data to the database.
When reaching around 10.000-13.000 the above error occurs (without further information) and its not longer usable. 

**To Reproduce**

1. run this kind of query more then 10.000 times in a row
```
INSERT INTO products (_id,title,articleNumber)
VALUES ('${product._id}','${product.title},'${product.articleNumber}');
```

**Expected behavior**
- SQLITE should not stop working
- Database connection should be able to open
- Get a more detailed error to be able to fix it

**Screenshots**
![Bildschirmfoto 2021-06-22 um 11 13 44](https://user-images.githubusercontent.com/47848371/122898135-eea89b80-d34a-11eb-87bf-11d5844fff82.png)

**Version**
`3.0.0-rc.2`

**Smartphone (please complete the following information):**

- Device: iPad Pro 5th generation (XCode simulator) 
- OS: iOS 14.5

**Comment by jepiqueau** [comment]
@NicolasHofmairT23 it is not clear enough to answer. Hope you do not open a connection each time you do an insert. You may look to use  multiple execute or executeSet command to load your database. The advantage of doing so is that you will begin a transaction and end a transaction only a the beginning and end of an execute or executeSet command instead of opening and ending at each insert. May be you could share part of your code so I could understand and reproduce the issue.

**Comment by NicolasHofmairT23** [comment]
@jepiqueau Thank you for your fast reply! 👍 
I think you are right here, it may be caused by too much opened connections.
I am doing this `db.open()` a lot of times. And it looks like I forgot to do `db.close()` for all of them. Now it looks like it is working after putting `db.close()` after each open statement.
I am still not too sure what it actually means but it was not working if I did not do this in the first place.

So it can be closed I guess, I think the issue was not doing this `db.close()`

**Comment by jepiqueau** [comment]
@NicolasHofmairT23 yes you should not re-open a db without closing it. So I close the issue
