### ISSUE TITLE
Error: Attempt to invoke virtual method '...' on a null object reference

### ISSUE THREAD

**Issue by baio** [capacitor-community/sqlite#150]
**Describe the bug**
Call on any `SQLiteConnection` method after plugin initialization gives error

Example for `echo`

```
Angular is running in development mode. Call enableProdMode() to enable production mode.
sq-lite.service.ts:29 *** platform android
sq-lite.service.ts:33 $$$ in service this.isService true $$$
app.component.ts:21 $$$ in App  this.initPlugin  true
sq-lite.service.ts:43 &&&& in echo this.sqlite [object Object] &&&&
tab1:231 native CapacitorSQLite.echo (#70882479)
tab1:205 result CapacitorSQLite.echo (#70882479)
tab1:213 {message: "Attempt to invoke virtual method 'java.lang.String…cho(java.lang.String)' on a null object reference"}
(anonymous) @ tab1:213
cap.fromNative @ tab1:416
(anonymous) @ VM476:1
core.js:6456 ERROR Error: Uncaught (in promise): Error: Attempt to invoke virtual method 'java.lang.String com.getcapacitor.community.database.sqlite.CapacitorSQLite.echo(java.lang.String)' on a null object reference
Error: Attempt to invoke virtual method 'java.lang.String com.getcapacitor.community.database.sqlite.CapacitorSQLite.echo(java.lang.String)' on a null object reference
    at Object.cap.fromNative (tab1:429)
    at <anonymous>:1:18
    at resolvePromise (zone.js:1255)
    at zone.js:1162
    at zone.js:1178
    at ZoneDelegate.invoke (zone.js:400)
    at Object.onInvoke (core.js:28673)
    at ZoneDelegate.invoke (zone.js:399)
    at Zone.run (zone.js:160)
    at zone.js:1318
    at ZoneDelegate.invokeTask (zone.js:434)
    at Object.onInvokeTask (core.js:28660)
```

**To Reproduce**

1. Clone `https://github.com/baio/vow-docs`
2. `npm install`
3. `npx cap sync`
4. build
5. deploy to device

Open chrome inspector, see error.

**Expected behavior**
Method should be called without any error

**Screenshots**
![image](https://user-images.githubusercontent.com/811593/126302105-fc79e33a-9542-4c79-b1b2-392219fc229b.png)

**Desktop (please complete the following information):**

- OS: windows 10
- Browser chrome

**Smartphone (please complete the following information):**

- Device: GALAXY S21 5G
- OS: Android 11
- Browser  stock browser

**Additional context**
It was working but after I updated some packages (not related to capacitor and even ionic) it stops. For couple of past two days I've tried all possible suggested trouble shouting and even create new project, still problem persists.

Also other capacitor plugins working as expected

**Comment by jepiqueau** [comment]
@baio First thanks for using the plugin and thanks to provide an example app.
do the following
- delete the android folder from your app
- npx cap add android
- go to android variables.gradle file and update `minSdkVersion = 23`
- npm run build
- npx cap copy
- npx cap open android
Now it should work. Since Capacitor 3 it is always better to delete android and ios folder and add them.

Hope this will be helpful

**Comment by baio** [comment]
@jepiqueau Thank you for quick response ! Just did exact steps you suggested unfortunately exactly same error ((

**Comment by jepiqueau** [comment]
@baio i do not understand, i git clone your project and did exactly what i said and it works fine 
npm version 7.6.0 
node version v14.15.4
macOS Big Sur version 11.4

**Comment by baio** [comment]
@jepiqueau 


node 16.0
npm 7.11.1
OS Windows 10

Yes something off here, it use to work in my environment, but now stops ((
BTW Have you checked it just after pulling repo without any modification, I believe it would work for you immediately

Thanks for your time.

**Comment by Glavotaner** [comment]
@baio Hey, I've been unable to reproduce your issue but I had the exact same error type recently. I suggest you debug your app while having logcat (eg. in Android Studio) open and check whether you have any SQLite related exceptions before the exception in this issue. For me the issue happened because there was an error during the invocation of the CapacitorSQLite.load() method in the Java side of the plugin, but I could only see that error in logcat. The error was cause by the part of the method which sets up the crypto shared preferences.

This is the error message I was receiving: 
https://stackoverflow.com/questions/55665337/keystoreexception-signature-mac-verification-failed-when-trying-to-decrypt

If you verify that this is the error you're also getting, the solution cited is to go into your app's AndroidManifest.xml and set android:allowBackup="false" within the application tag. I don't have enough experience to fully know the consequences of changing that value so perhaps before you go ahead and do it, you should either research what this means for your app, or there could be some comments from people in this community regarding that.

Hope this helps.

**Comment by baio** [comment]
@Glavotaner Thank you very much it was exactly the same problem. But I couldn't get rid of it even with `android:allowBackup="false"` till turn off debug mode and then on it on device.

@Glavotaner @jepiqueau  Thanks for help !

**Comment by jepiqueau** [comment]
@baio it should be then a cache issue it also explain why it was working when i clone it as the app was new on my machine. Please that you find the solution good luck for your app

**Comment by rkreutzer** [comment]
I had a similar issue, but before doing the steps above, I had to rename my local project folder, then re-clone my git repository to my local machine. Then deleting the android folder and rebuilding the app worked.
