### ISSUE TITLE
Can someone make a wiki for new developer to use this?

### ISSUE THREAD

**Issue by chiqors** [capacitor-community/sqlite#193]
Please, for god sake.. I am confused with the readme file.. What is going on?

**Comment by jepiqueau** [comment]
@chiqors thanks for looking at the plug-in. Can you develop a bit. Did you look at the documentation in the docs folder and at the application starters referenced in the readme.
Which framework do you want to use ?

**Comment by chiqors** [comment]
i am developing application based on quasar framework. I would love to use this plugin. But, i don't know where to start.

**Comment by jepiqueau** [comment]
@chiqors I do not know the quasar framework but it is based on Vue framework so look at the vue-sqlite-app-starter  and vue-sqlite-app this will help you to start. Are you looking for native app ( iOS, Android) or Electron. The Web part of the plug-in has been made to help for a quick test implementation before to move to native.

**Comment by chiqors** [comment]
i am looking for native app, android with the help of capacitor

**Comment by jepiqueau** [comment]
@chiqors I assume that you do not want to use Ionic/Vue so may be you can look at https://github.com/jepiqueau/vue-capacitor-sqlite-issue137 it could help you to start

**Comment by jepiqueau** [comment]
@chiqors did you succeed to do something ?

**Comment by chiqors** [comment]
i guess so.. i mught need to learn more of how sqlite work with js

**Comment by jepiqueau** [comment]
@chiqors ok if you have any question you are welcome. Some developers have successfully use it with Quasar.

**Comment by tobiasmuecksch** [comment]
To be honest, the documentation is really really confusing. Event for experienced developers. For example: When using the `createConnection()` method, you need to specify several parameters. The third is called `mode`. I'm scanning through the documentation to find a hint on what exactly this mode is, and which values I can give it. Until now, I had no luck....

**Comment by jepiqueau** [comment]
@tobiasmuecksch did you look at the API.md under the docs folder. There are also application staters for different frameworks which will guide you under https://github.com/jepiqueau. But all the links to the statère apps are also in the readme.md file

**Comment by tobiasmuecksch** [comment]
Sure I did. And I really appreciate the work, there massive amounts of stuff. But it is very complicated. For now I don't want a predefined singleton service. All I need to understand the core concepts is some examples about:

1. How to create a connection
2. How to setup a database
3. How to query a database
4. How does the versioning and upgrading work?
5. Some best practices and advices (for example should a close a connection after every query, or can I leave them open for ever and re-use them)


I do understand, that most of these questions can be answered by looking at the provided demo code, but because the code very complicated, it takes hours to find even the simplest information.

In the meantime I found out, that `mode` can have these values: `["encryption", "secret", "newsecret"]`, but what is the difference? What das each value mean? Do I even have to provide that value if I set the `encryption` parameter to false?

**Comment by jepiqueau** [comment]
@tobiasmuecksch what is the framework you intent to use ?

**Comment by tobiasmuecksch** [comment]
In the end, I will use ionic/angular/cap3.

But I want to understand this plugin without any framework related information as far as possible. I only want to know how to use it with simple TypeScript. No singleton services or anything else. I want to create my own service.

**Comment by tobiasmuecksch** [comment]
The best introduction I could think of would look like this (just pseudo code, I know that most of it is wrong):


```typescript
 
import {CapacitorSQLite} form '@capacitor/sqlite';

// Establish connection
const connection = new CapacitorSQLite();

// Setup database
json = '{ .... }'; // shortened
connection.setupDatabase({databasename: 'users', schema: json, version: 2})
connection.addUpgrade({databasename: 'users', statements: [{query: 'UPDATE TABLE'}], version: 2});

// get database specific connection 
const database = connection.openDatabase({databasename: 'users', version: 2});

// Query the database
const result = await database.query('SELECT * FROM users WHERE username = ?', ['bob']);

```
