### ISSUE TITLE
Problems with DELETE FROM

### ISSUE THREAD

**Issue by s3vdev** [capacitor-community/sqlite#285]
**Describe the bug**
When attempting to call a delete statement using multiline strings, e.g.
```
let query = `
  DELETE FROM sample_table
  WHERE col_1 = ?
    AND col_2 = ?
`;
```
the following error occurs:
`Error: Run: near "FROM": syntax error: , while compiling: UPDATE TE FROM sample_table SET sql_deleted = 1 WHERE col_1 = ?
        AND col_2 = ?`

Rewriting the query onto a single line, regardless of with backticks or apostrophes as string delimiters, leads to the following error:
`Error: Run: near ",": syntax error: , while compiling: UPDATE sample_table SET sql_deleted = 1 WHERE col_1, col_3 = ? AND col_2 = ?`

Directly updating the sql_deleted column appears to work, nonetheless it would be nicer if deletion worked as well.
Tested on an Android emulator running Android 11.

**Expected behavior**
Presumably, a query along the lines on `UPDATE sample_table SET sql_deleted = 1 WHERE col_1 = ? AND col_2 = ?` would be executed.

**Smartphone:**

- Device: Android emulator (Pixel C)
- OS: Android 11

**Comment by Sampath-Lokuge** [comment]
This works for me

```
  private deleteExtrasByFareId(fareId: string): Promise<capSQLiteChanges> {
    const sqlQuery = `DELETE FROM Extras WHERE FareId=?`;

    const sqlValues = [fareId];

    return this.sqliteDbConnection.run(sqlQuery, sqlValues, false);
  }
```

**Comment by jepiqueau** [comment]
@s3dev i do not understand the ' , col3 = ? ' comes from. There are some zpps demonstrating the use of the delete command on my site which works. capacitor-solid-sqlite is the one i use to test

**Comment by jepiqueau** [comment]
@s3vdev any progress on this

**Comment by s3vdev** [comment]
@jepiqueau Regarding "col_3", the table in question has nine columns (col_1 through col_9) plus "sql_deleted" and "last_modified".
For some reason, the third column gets included, although the original statement only has the first two.
That said, changing the query to only include col_3 (`DELETE FROM sample_table WHERE col_3 = ?`) however produces `Error: Run: near ",": syntax error: , while compiling: UPDATE sample_table SET sql_deleted = 1 WHERE col_1, col_3 = ?`

I've had a look through capacitor-solid-sqlite, and I've noticed that the delete statements' where clauses reference at most one column.
My problem could be due to my table (all tables in my current project) requiring composite primary keys...
Could you say whether the delete statement conversion supports multiple column references in the where clause, alternatively if it correctly converts for tables with composite primary keys?

**Comment by jepiqueau** [comment]
@s3vdev you right composite primary keys have not been implemented as well as foreign key with multiple WHERE clause

**Comment by jepiqueau** [comment]
@s3vdev this has been fixed in 3.5.2. can you test it and revert to me

**Comment by jepiqueau** [comment]
@s3vdev Having no return from you, i assume it has been fixed. It was quite a job to to it, so at least i was hoping some follow up from your side. I will close then the issue

**Comment by MonicaExplan** [comment]
Hi
moving from 3.5.1 to 3.5.2 I have a delete problem.
The problem seems to occur when I do a delete on
a linked table (foreign key on the main with ON DELETE CASCADE).
If from the ticketsAssets table schema I remove this

{ "foreignkey": "ticketId", "value": "REFERENCES tickets(id) ON DELETE CASCADE" }

the error does not occur

----
to. the main table
{
         "name": "tickets",
         "pattern": [
           { "column": "id", "value": "INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL" },
           { "column": "syncId", "value": "TEXT UNIQUE" },
           { "column": "num", "value": "TEXT UNIQUE" },
           { "column": "subject", "value": "TEXT NOT NULL" },
           { "column": "location", "value": "TEXT" },
           { "column": "roomId", "value": "TEXT" },
           { "column": "roomSyncId", "value": "TEXT" },
           { "column": "siteId", "value": "TEXT" },
           { "column": "siteSyncId", "value": "TEXT NOT NULL" },
           { "column": "servicelevelsId", "value": "TEXT" },
           { "column": "servicelevelsSyncId", "value": "TEXT" },
           { "column": "categoryId", "value": "TEXT" },
           { "column": "categorySyncId", "value": "TEXT" },
           { "column": "subcategoryId", "value": "TEXT" },
           { "column": "subcategorySyncId", "value": "TEXT" },
           { "column": "status1", "value": "TEXT DEFAULT 'To be sent'" },
           { "column": "status2", "value": "TEXT" },
           { "column": "insertDateTime", "value": "TEXT" },
           { "column": "recordType", "value": "INTEGER DEFAULT 0 NOT NULL" },
           { "column": "editable", "value": "INTEGER DEFAULT 0 NOT NULL" },
           { "column": "deletable", "value": "INTEGER DEFAULT 0 NOT NULL" },
           { "column": "last_modified", "value":"INTEGER DEFAULT (strftime('%s', 'now'))" },
           { "column": "sql_deleted", "value": "BOOLEAN DEFAULT 0 CHECK (sql_deleted IN (0, 1))" }
         ]
}

b. this is my linked table
{
         "name": "ticketsAssets",
         "pattern": [
           { "column": "id", "value": "INTEGER PRIMARY KEY NOT NULL" },
           { "column": "ticketId", "value": "TEXT" },
           { "column": "ticketSyncId", "value": "TEXT" },
           { "column": "assetId", "value": "TEXT" },
           { "column": "assetSyncId", "value": "TEXT" },
           { "column": "recordType", "value": "INTEGER DEFAULT 0 NOT NULL" },
           { "column": "editable", "value": "INTEGER DEFAULT 0 NOT NULL" },
           { "column": "deletable", "value": "INTEGER DEFAULT 0 NOT NULL" },
           { "column": "last_modified", "value": "INTEGER DEFAULT (strftime('%s', 'now'))" },
           { "column": "sql_deleted", "value": "BOOLEAN DEFAULT 0 CHECK (sql_deleted IN (0, 1))" },
           { "foreignkey": "ticketId", "value": "REFERENCES tickets(id) ON DELETE CASCADE" }
         ]
}



----- This is the error log
File: https://y7r5nre1wi31w1uvlrdv/js/chunk-cc2c78c8.bae03cba.js - Line 1 - Msg: [{"statement":"DELETE FROM ticketsAssets WHERE ticketSyncId=?;","values":["9400E607EAF78F4FC1258B01004C8624"]} ]
2024-04-16 16:30:36.127 9131-9131 Capacitor/Plugin it.explan.plangei.consumer V To native (Capacitor plugin): callbackId: 85579387, pluginId: CapacitorSQLite, methodName: executeSet
2024-04-16 16:30:36.131 9131-9131 Capacitor it.explan.plangei.consumer V callback: 85579387, pluginId: CapacitorSQLite, methodName: executeSet, methodData: {"database":"consumer_plangei_","set":[ {"statement":"DELETE FROM ticketsAssets WHERE ticketSyncId=?;","values":["9400E607EAF78F4FC1258B01004C8624"]}],"transaction":false}
2024-04-16 16:30:36.132 9131-9287 Capacitor/Plugin it.explan.plangei.consumer W getArray calls without a default value will return null in Capacitor 5 instead of an empty array to match iOS behavior
2024-04-16 16:30:36.136 9131-9287 com.getcap...RetHandler it.explan.plangei.consumer V *** ERROR ExecuteSet: incomplete input: , while compiling: UPDATE tickets SET sql_deleted = 1 WHERE
2024-04-16 16:30:36.136 9131-9287 Capacitor en.explan.plangei.consumer D Sending plugin error: {"save":false,"callbackId":"85579379","pluginId":"CapacitorSQLite"," methodName":"executeSet","success":false,"error":{"message":"ExecuteSet: incomplete input: , while compiling: UPDATE tickets SET sql_deleted = 1 WHERE "}}

thanks a lot
Monica
