### ISSUE TITLE
QUESTION: best practices for using SQLite connections in Vue/JS?

### ISSUE THREAD

**Issue by moksamedia** [capacitor-community/sqlite#293]
Can someone point me to a guide on best practices for SQLite usage in Vue? Particularly with regard to connection management. Or just answer here. 

I'm writing an app and abstracting out my SQLite access into a database module. I'm not sure how often I should be creating and closing connections. Should every function open a new connection and close it? Should each Vue module create a connection when it is mounted and close it on unmount? Should I create a global database connection that every transaction goes through? How global or local should the connection management be?

Any help would be appreciated.

Andrew

**Comment by jepiqueau** [comment]
@moksamedia there are several vue app example i n https://github.com/jepiqueau even if there are not all updated that will help you to start. You have to avoid to open and close a connection in every of your functions this is time consuming. in your function you just test if the connection is open in case not you open it otherwise you retrieve it

**Comment by jepiqueau** [comment]
@moksamedia Assuming you found what you need So i close the issue Fell free to re-open it if required
