### ISSUE TITLE
feat(iOS): read sqlite fie from files app which location is "On my iPhone" or iCloud path

### ISSUE THREAD

**Issue by aquarius-wing** [capacitor-community/sqlite#337]
# Request
I want capacitor can reader the sqlite file out side the app, just like device itself filesystem, and connected filesystem like nas.

# The way I try
I read the capacitor api doc, and none of FilesystemDirectory's value can read or save sqlite out side the app.
If there is another way to get through it, please tell me.

# Wish
The app I want to build, just like obsidian iOS app which can read files in any directory of iCloud.

**Comment by jepiqueau** [comment]
@aquarius-wing i saw your comment. I do not think i will look at this as for me the database are application dependent and having database share on the iCloud path is not really a good idea for security. Developers were asking to have under Library and not documents folder just because the documents folder is shared on iCloud.

**Comment by aquarius-wing** [comment]
I see, thank you.
