### ISSUE TITLE
Allow users to set secret

### ISSUE THREAD

**Issue by felixerdy** [capacitor-community/sqlite#88]
**Is your feature request related to a problem? Please describe.**
I'd like to provide users a way to set the secret for an encrypted database by themselves. Currently, it's only possible (as far as I'm aware of) to define the secret before building the app in [different files, depending on the platform](https://github.com/capacitor-community/sqlite/blob/master/docs/API.md#defining-your-own-secret-and-newsecret-keys-encryption-only)

**Describe the solution you'd like**
- When [creating](https://github.com/capacitor-community/sqlite/blob/master/docs/API.md#createconnection) a DB connection, provide a `secret` and `newsecret` property to the [capConnectionOptions](https://github.com/capacitor-community/sqlite/blob/master/docs/API.md#capconnectionoptions) to be able to define both values by users
- When [opening](https://github.com/capacitor-community/sqlite/blob/master/docs/API.md#open) a DB connection, provide a `secret` property to the [capSQLiteOptions](https://github.com/capacitor-community/sqlite/blob/master/docs/API.md#capsqliteoptions) so that users can insert their secret key
- Add according error handling / messages

**Additional context**
If I am building an app and distributing it to multiple users, it seems like a security issue to me if all databases are using the same secret key

**Comment by jepiqueau** [comment]
@felixerdy It was done like this in early release, but people where complaining that it was not safe to do it that way and were asking to have it in the App so i do not know what is the right answer for this issue

**Comment by noerw** [comment]
Having the key in the app source code is not safe either. The key is public, 
Much less safe even, as it will be the same for all apps using this plugin unmodified.

The right way to do this for Android imho is:
- add password flag for app and/or user-provided to DB open constructor
- generate random key on DB creation
- store the random key in android's [KeyStore](https://developer.android.com/reference/java/security/KeyStore.html), protect access with the user provided password.

I'm not very knowledgeable about iOS or electron, but similar facilities probably exist there too.

If user provided passphrases are not an option, at the very least the key should be generated from a device ID, so attackers can't decrypt any db generated by this plugin without further knowledge.
Otherwise, the "encryption" provided is pretty useless.

@jepiqueau Can you link the discussion where providing a user-generated key was considered unsafe, so we don't start the discussion all over?

**Comment by jepiqueau** [comment]
@noerw thank you for opening the discussion with a proposal, the solution must also contains the migration of existing encrypted databases using the current way. I think this have to be done on the release 3 beta of the plugin.
Can you contribute for the android part following your proposal , i will review it and if it works well and accepted by the capacitor developer community, i will implement something similar for iOS and Electron.

**Comment by jepiqueau** [comment]
@noerw the password can also be stored in Android Shared Preferences which is a key value store persisting when the app is close. The value could be encrypted with the device ID's

**Comment by jepiqueau** [comment]
@noerw i will start looking at this issue. i will use `EncryptedSharedPreferences` class part of the Android Jetpack Security library to store the encrypted given secret. I will make a first release for `@capacitor-community/sqlite@next` Android plugin. Will you be in position to test it and tell me if the process used is secure enough?
i will updated the open command to look for an encrypted store secret and re-encrypt the database  if it was encrypted with the Global secret or encrypt it if it was not encrypted

**Comment by jepiqueau** [comment]
@noerw @felixerdy This has been fixed in @capacitor-community/sqlite@3.0.0-beta.13
